### ISSUE TITLE
Incompatibility with "LethalPipeRemoval" & partial incompatibility with other "poster mods"

### ISSUE THREAD

**Issue by Fl4sHNoX** [jverif/lc-shipwindow#15]
It seems that when purchasing a window through the terminal it "overrides" the settings set with [LethalPipeRemoval](https://github.com/d-rafferty/lethal-tube-removal) and uses the default interior, as you can see in the following images:

![image](https://github.com/jverif/lc-shipwindow/assets/3759901/cf4ee2a4-6820-45f8-b178-f4f05b411b70)

![image](https://github.com/jverif/lc-shipwindow/assets/3759901/85d7e21d-5750-46d8-9c08-93b237bf0a1a)

Also, whenever purchasing the "Right Window" (the one that moves the posters), the posters default back to the vanilla ones as well.
This however seems to only occur until landing on a moon after purchasing the window through the store.

**Comment by d-rafferty** [comment]
I'll take a look and see what's going on.

**Comment by d-rafferty** [comment]
In the readme I do notice it says this mod is incompatible with LethalPosters. Could that be the cause of your issue perhaps?  I wish I could be more helpful but I cannot seem to recreate this bug in my game. My best guess would be try disabling LethalPosters and see if that resolves your issue.

**Comment by Fl4sHNoX** [comment]
> In the readme I do notice it says this mod is incompatible with LethalPosters.

I can't seem to find that in the readme?

**Comment by d-rafferty** [comment]
![Screenshot 2024-03-17 184244](https://github.com/jverif/lc-shipwindow/assets/90558421/6cfe418b-2267-4b53-a724-db8a050f9a7a)

**Comment by Fl4sHNoX** [comment]
Oh my bad I confused the two and thought you were the author of ShipWindows so I was checking LethalPipeRemoval's readme!

**Comment by jverif** [comment]
Also just wanted to note, I have fixed issues with custom posters in a recent commit, but I haven't uploaded it to the Thunderstore yet. Just have a few more things I want to do first.
