### ISSUE TITLE
Very small "issue" related to posters edited with LethalPoster & the "Left Window"

### ISSUE THREAD

**Issue by Fl4sHNoX** [jverif/lc-shipwindow#16]
I just wanted to make a small note by illustrating the issue in case some people see it happen and wonder about it, although I now know that there's a mention of it in the Compatibility section of the readme:

![image](https://github.com/jverif/lc-shipwindow/assets/3759901/038168cd-e823-40d6-a16c-5898bf0ae281)

Description:

Whenever purchasing the "Left Window" (the one that moves the posters), the posters default back to the vanilla ones.
This however seems to only occur until landing on a moon after purchasing the window through the store.

Here's what it looks like:

https://github.com/jverif/lc-shipwindow/assets/3759901/cdb1b5d8-6918-43a9-857c-9a02107bf1a1

**Comment by jverif** [comment]
This will be fixed in the next update. Sorry for the late reply. I hadn't checked my email in a few days.
