### ISSUE TITLE
Small issue when losing a game

### ISSUE THREAD

**Issue by ZigzagAwaka** [jverif/lc-shipwindow#17]
Very small issue concerning the already unlocked windows (with the UnlockWindow# configs).
It seems that when the crew is fired, these windows are removed from the ship even if they should be unlocked by default (however, since the game just restarted, it can be fixed by closing the game and starting a new one)

**Comment by jverif** [comment]
It's currently supposed to account for that. Do you have any mods that would affect furniture or unlockables / upgrades in any way?

**Comment by ZigzagAwaka** [comment]
I don't think so, I tested this issue with a small profile of 50 mods (mostly moons and monsters) but the issue was still present
You can check this profile if you want 018e6dad-d654-d3c2-9221-132f301e5cb7
I can't share a profile file since github dosn't allow it

**Comment by ZigzagAwaka** [comment]
In case the profile code is dead, here is a Google Drive share link of my profile file:
https://drive.google.com/file/d/1Eu9T3INI2H4H7QiHI3wcs70cTOKzqK-N/view?usp=sharing

**Comment by ZigzagAwaka** [comment]
By using another profile the issue was solved (strangely)
Since it most likelly comes from an unknown mod, it's ok if you don't want to find the problem, I totally understand that
You can close the issue, no worries

**Comment by ZigzagAwaka** [comment]
I'm closing the issue, thanks again for this great mod

**Comment by jverif** [comment]
I did delay the routine a bit just in case there was a timing issue, and that may have fixed your particular issue, but might not be a good permanent solution. I'll check out the mod list to see if there's something going on.
