### ISSUE TITLE
[Question] so i don't know how to find author name call "Verity" but ur name are similar with that, so uh maybe u can contact that author bc so many issues with "toomanysuit"

### ISSUE THREAD

**Issue by CoolLKKPS** [jverif/lc-shipwindow#19]
uh hope u don't mind bc i cannot use discord

**Comment by jverif** [comment]
If it's related to v50, I'm sure they will upload an update after the official release. I think a few people are waiting since updates on the beta branch are still ongoing.

What issue are you having?

**Comment by CoolLKKPS** [comment]
so previously i found some conflict with lobby control mod when using toomanysuit, so i create a issue ticket in there: https://github.com/mattymatty97/LTC_MattyFixes/issues/1<https://github.com/mattymatty97/LTC_MattyFixes/issues/1#issuecomment-2037668542>
this mod not only have conflict, but when u loading the map with other player and quit to main menu as host, will cause some error, but that mod is not update for too long so, those issues are really need to fix like rn

**Comment by CoolLKKPS** [comment]
some typo fixed
