### ISSUE TITLE
Compatibility with ShipMaid

### ISSUE THREAD

**Issue by worldofrich** [jverif/lc-shipwindow#2]
It appears when this mod is enabled, when using ShipMaid which will organize items into the storage cabinet and items on the floor, it appears to make the items spawn off the ship somewhere or make them invisible. The loot is still registered as on the ship, but is not visible any player.

**Comment by jverif** [comment]
I will check to see what could be causing this. Ship Windows spawns a new prefab to act as the `HangarShip/ShipInside` object, and disables the original. So my guess is that could be causing issues.

**Comment by jverif** [comment]
This should hopefully be fixed with the next update, which will be 1.3.0.
