### ISSUE TITLE
[Suggestion] Close shutters when switching planets

### ISSUE THREAD

**Issue by Pahheb** [jverif/lc-shipwindow#21]
When switching planets with the "Celestial Tint" mod, the skybox deloads, resulting in a solid dark grey color, and then loads the new one, which can be observed through the windows.

For this reason, I suggest closing the window shutters when a new planet is selected and then re-opening them once the new skybox has loaded, for a more immersive experience.

**Comment by Test-Account666** [comment]
Added in my continuation of this mod:

https://thunderstore.io/c/lethal-company/p/TestAccount666/ShipWindows/
