### ISSUE TITLE
[Suggestion] High quality & animated space skybox

### ISSUE THREAD

**Issue by DaedalusGH** [jverif/lc-shipwindow#6]
_I absolutely love this mod, I created a Github account because I wanted to leave this suggestion. It's a small mod but it adds a lot, i'm a sucker for pretty visuals.
I don't know much about coding so please forgive me if this is a tall request, it's a great mod wether or not you choose to do this suggestion._
The current space skyboxes are great, although in my opinion it does feel a bit "fake" if you know what I mean. **The image is very low quality and completely static, which makes the outside view from the windows strange sometimes, especially when put up to close scrutiny over many hours of play.**

My exact suggestion would be for a higher quality image of space that is also animated. 
The skybox could slowly rotate overtime to help sell the illusion of really being in space, as well as the higher quality of the image helping the skybox stand up to close scrutiny over many hours of play. 
The image could also be different from the other two skyboxes, something that isn't as bright as the 2nd skybox, and isn't as subtle as the 1st skybox. Perhaps it could even be a GIF, although I don't know if that's difficult to implement. Rotating the skybox is probably more than enough to really sell the illusion of being in space. :)

_Thank you for listening, and thank you for making the mod! It's one of my favorites out of my modpack, and i'm excited for every update!_

**Comment by DaedalusGH** [comment]
I'm really excited for stuff like this because I spend a lot of time in orbit. Waiting for friends to join/get ready, buying things, mentally preparing for the next moon, stuff like that. Since I spend so much time in orbit, I love any mod that makes being in orbit a little more pretty or fun. I would absolutely adore a high quality spinning skybox of space, my friends and I would definitely stare out the windows a lot just watching the stars go by haha. It would definitely be trippy if the skybox rotated on 2 axes at the same time instead of just rotating in 1 direction, which would really help create the feeling of drifting around in orbit. I also don't mind large file sizes, my friends don't either. Thank you! :D

**Comment by jverif** [comment]
I had 4K textures of the skybox, so I've gone ahead and swapped out the lower res ones I was using. I've also added a slow rotation to both skyboxes. Unfortunately, the HDRI Sky volume doesn't let me control rotation on more than one axis. The workaround is to use a second camera and rotate it instead, which is a little dirty in my opinion. I think it still looks fine, though.

Thanks for the suggestions!

**Comment by DaedalusGH** [comment]
AHHHH THIS WAS SO COOL TO WAKE UP TO! THANK YOU! THIS IS SO AWESOME
