### ISSUE TITLE
Missing Texture? Random Brush?

### ISSUE THREAD

**Issue by Aeniema** [jverif/lc-shipwindow#8]
I don't know if it's a WIP part of the mod, bad there's landscape missing texture below the ship? Sorry if aware. <3

![image](https://github.com/jverif/lc-shipwindow/assets/117127021/f45c2761-55a7-495b-9005-00e543238ae7)

**Comment by Aeniema** [comment]
Unsure if it's related specifically to this mod, it may be something that didn't unload/get destroyed when - also messing with HDLethal Somehow fixed it for me. I am much confused haha.

**Comment by jverif** [comment]
This is a terrain Lethal Expansion creates to preload some information. It doesn't look like it cares about its position, so I'm adding a patch to move it off somewhere truly out of view in the next update.

**Comment by jverif** [comment]
Fixed with 1.3.4
